[WIP] added PUT /transfers/transferId handling for notifications to payee
mojaloop/sdk-scheme-adapter pull request #194
Opened 2020-08-17 15:04 UTC by vgenev

Thats draft PR for review purposes.
Tests are still missing.

2020-08-18 11:02 UTC, rmothilal commented
@vgenev as per @bushjames comments I think we should remove the retry logic and create a story to update all requests within the sdk to have retry logic. Then continue with your current changes for the patch fucntionality

2020-08-20 11:25 UTC, bushjames requested changes

2020-08-20 11:25 UTC, bushjames commented on src/lib/model/InboundTransfersModel.js
> +            this._logger.push({ err }).log('Error in getParticipants');
copy/paste problem here @vgenev .... should be `Error in sendNotificationToPayee` I think.

2020-08-20 14:28 UTC, bushjames approved these changes

2020-08-20 14:29 UTC, merged