refactor: rework party lookup loop
mojaloop/sdk-scheme-adapter pull request #378
Opened 2022-09-16 03:24 UTC by kleyow

2022-09-20 06:27 UTC, vijayg10 requested changes

2022-09-20 06:27 UTC, vijayg10 commented on modules/private-shared-lib/src/infra/redis_bulk_transaction_repo.ts
> +            const newValue = await this._redisClient.hIncrBy(key, this.bulkQuotesSuccessCountKey, 1);
```suggestion
            const newValue = await this._redisClient.hIncrBy(key, this.bulkQuotesSuccessCountKey, increment);
```

2022-09-20 06:27 UTC, vijayg10 commented on modules/private-shared-lib/src/infra/redis_bulk_transaction_repo.ts
> +            const newValue = await this._redisClient.hIncrBy(key, this.bulkQuotesFailedCountKey, 1);
```suggestion
            const newValue = await this._redisClient.hIncrBy(key, this.bulkQuotesFailedCountKey, increment);
```

2022-09-20 14:27 UTC, kleyow commented on modules/private-shared-lib/src/infra/redis_bulk_transaction_repo.ts
> +            const newValue = await this._redisClient.hIncrBy(key, this.bulkQuotesSuccessCountKey, 1);
good catch, thanks. done.

2022-09-22 09:23 UTC, mdebarros approved these changes
+1

@kleyow we also need to get this change into the main mvp branch and the transfers feature branch.

2022-09-22 12:49 UTC, merged