fix(mojaloop/3137): bulk transactions sdk crash
mojaloop/sdk-scheme-adapter pull request #439
Opened 2023-02-21 07:21 UTC by vijayg10

fix([mojaloop/3137](https://github.com/mojaloop/project/issues/3137)): bulk transactions sdk crash

2023-02-21 07:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mojaloop/sdk-scheme-adapter?pullRequest=439) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mojaloop/sdk-scheme-adapter?pullRequest=439) before we can accept your contribution.<br/><hr/>**Vijay Kumar Guthi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mojaloop/sdk-scheme-adapter?pullRequest=439) it.</sub>

2023-02-27 13:17 UTC, mdebarros approved these changes
LGTM except for the failing CI checks.

Please investigate.

2023-02-27 13:18 UTC, mdebarros requested changes
Pls fix CI checks

2023-02-27 15:56 UTC, vijayg10 commented
Duplicate of https://github.com/mojaloop/sdk-scheme-adapter/pull/439

2023-02-27 15:56 UTC, closed without merging